version: '1'
services:
  app:
    build: .
    working_dir: /
    environment:
      NODE_ENV: development
    tty: true
    ports:
      - "8030:80"
    links:
      - mongo
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"