version: '3'
services:
  betty:
    build: .
    container_name: betty
    labels:
      traefik.enable: "true"
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    tty: true
    ports:
      - "8484:8484"
    links:
      - mongo
  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"